{
    'name': 'Ancestry',
    'version': '1.0',
    'summary': 'Manage family trees',
    'description': 'A custom app with content',
    'author': 'Ben Foley',
    'category': 'Ancestry',
    'depends': [ 'portal', 'website', 'website_sale' ],
    'data': [
        'security/ancestry_groups.xml',
        'security/ir.model.access.csv',
        'views/ancestry_event_views.xml',
        'views/ancestry_media_views.xml',
        'views/ancestry_source_views.xml',
        'views/ancestry_tree_member_views.xml',
        'views/ancestry_source_views.xml',
        'views/ancestry_tree_views.xml',
        'views/ancestry_views.xml',
    ],
    'demo': [
        'demo/ancestry_ancestry_demo.xml',
        'demo/ancestry_tree_demo.xml',
        'demo/ancestry_tree_member_demo.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}
