FROM python:3.12-slim

ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_ENVIRONMENT=development

WORKDIR /app

COPY app/requirements/base.txt /app/requirements/
COPY app/requirements/development.txt /app/requirements/

RUN pip install -r requirements/development.txt

COPY app/ /app