{
    'name': 'Ancestry',
    'version': '1.1',
    'summary': 'Store and organize client data for ancestry research',
    'description': 'The best app ever :)',
    'author': 'Ben Foley',
    'category': 'Ancestry',
    'depends': ['website', 'website_sale'],
    'data': [
        'security/ancestry_groups.xml',
        'security/ir.model.access.csv',
        'views/ancestry_event_views.xml',
        'views/ancestry_media_views.xml',
        'views/ancestry_source_views.xml',
        'views/ancestry_tree_member_views.xml',
        'views/ancestry_tree_views.xml',
        'views/ancestry_views.xml',
        'views/portal_templates.xml',
    ],
    # 'demo': [
    #     'demo/ancestry_ancestry_demo.xml',
    #     'demo/ancestry_tree_member_demo.xml',
    #     'demo/ancestry_tree_demo.xml',
    # ],
    'assets': {
        'web.assets_frontend': ['ancestry/static/src/js/util/hide.js'],
        # 'web.assets_backend': [],
        # 'web.assets_common': [],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}